### ISSUE TITLE
Fees Info

### ISSUE THREAD

**Issue by sanchaymittal** [connext/vector-modal#48]
problem: we should show message for first time users for fees, otherwise they would panic.

solution:
- a message describing, first time fees only per network
- we should link a tool tip to fees giving break of fees and link to docs

**Comment by LayneHaber** [comment]
Do you think this will need a corresponding router update to describe how the fees are broken down? I'm reasonably sure we can describe it without it, but not sure how detailed you were thinking

**Comment by sanchaymittal** [comment]
> Do you think this will need a corresponding router update to describe how the fees are broken down? I'm reasonably sure we can describe it without it, but not sure how detailed you were thinking

Hmm, I mean if it's easy then we should get this breakdown from router only. Otherwise we will be doing double calculation at front-end. Also matic could use this too.

fees breakdown:
- First time Channel creation fee
- recurring onChain fee
- Router fee

@LayneHaber

**Comment by LayneHaber** [comment]
I mean this would be kind of weird, and since were thinking of changing how fees work is likely going to be broken in someway in the near future. I would say a better option is to just have a tooltip that says what fees could come from, why its expensive for the first time, and why it varies. That'll be a lot easier to maintain, won't really break with AMM introduction, and users likely won't care why the router is taking fees beyond some reasonable explanation of the inherent costs

**Comment by sanchaymittal** [comment]
Tooltip is good idea for sure and easy to maintain, we can link it to a doc for deeper dive.
But i do think user's would be interested to know the fees breakdown, It feels more transparent with fees breakdown.

we always compare the fees charges by different exchanges, like how much liquidity provider is getting, network fee etc.
@LayneHaber @rhlsthrm

**Comment by rhlsthrm** [comment]
Yeah I think getting a router breakdown is not the way to go right now because of the changes we will be making to fees once we start networking the routers. For now, a static tooltip is probably fine.
